# Generated by Django 5.0.1 on 2025-01-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="reference_number",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Reference Number"
            ),
        ),
    ]
